/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio4;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author PorDefecto
 */
public class Ejercicio_4_Ciclos_pastor extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Ejercicio_4_Ciclos_pastor() throws IOException {
        initComponents();
        sacardatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabladatos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Asignatura", "Tipo", "Docente", "Ciclo", "Seccion", "Semestre"
            }
        ));
        jScrollPane1.setViewportView(tabladatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 344));

        jButton1.setText("Crear carpetas Ciclo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, -1));

        jButton2.setText("Copiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, -1));

        setSize(new java.awt.Dimension(861, 456));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String[][] datos = new String[tabladatos.getRowCount()][tabladatos.getColumnCount()];
    int i = 0;
    int j = 0;
    for (i = 0; i < tabladatos.getRowCount(); i++) {
        for (j = 0; j < tabladatos.getColumnCount(); j++) {                        
                                datos[i][j] = (String) tabladatos.getValueAt(i, j);
                    }
        }    
        File objeto1=new File("C:/EPIS/Ciclos");
        File objeto2=new File("C:/EPIS/Ciclos");
        File objeto3;
        File objeto4;       
        if (!objeto1.exists()) { objeto1.mkdir();}
        for (int k = 0; k < datos.length; k++) {
                    objeto3=new File("C:/EPIS/Ciclos/"+datos[k][4]);
                    objeto4=new File("C:/EPIS/Ciclos/"+datos[k][4]+"/"+datos[k][0]+" "+datos[k][1]+" "+datos[k][5]);
                    
                    if (!objeto3.exists()) {
                         objeto3.mkdir();
                    }
                    if (!objeto4.exists()) {
                         objeto4.mkdir();
                    }                 
       }
    }//GEN-LAST:event_jButton1ActionPerformed
public void sacardatos() throws FileNotFoundException, IOException{
      DefaultTableModel modelo=(DefaultTableModel) tabladatos.getModel();
     Object[] fila= new Object[modelo.getColumnCount()];
     int contador=0;
        File excelFile = new File("C:/EPIS/Carga2019-I.xlsx");
    FileInputStream fis = new FileInputStream(excelFile);
    XSSFWorkbook workbook = new XSSFWorkbook(fis);
    XSSFSheet sheet = workbook.getSheetAt(0);
    Row row;
    Iterator<Row> rowIt = sheet.iterator();
    while(rowIt.hasNext()) {
       row = rowIt.next();
                     String codigo=String.valueOf(row.getCell(1));
                     String curso=String.valueOf(row.getCell(2));
                     String tipo=String.valueOf(row.getCell(3));
                     String docente=String.valueOf(row.getCell(4));
                     String ciclo=String.valueOf(row.getCell(5));
                     String seccion=String.valueOf(row.getCell(6));       
                     String sementre=String.valueOf(row.getCell(7)); 
                     if(!codigo.equals("") && !codigo.equals("null") && !codigo.equals("Código") ){
                        if(!codigo.equals("") &&!curso.equals("") &&!tipo.equals("") &&!docente.equals("") &&!ciclo.equals("") &&
                         !seccion.equals("") &&!sementre.equals("")){    
                            String[] Datos=new String[7];
                                Datos[0]=codigo;
                                Datos[1]=curso;
                                Datos[2]=tipo;
                                Datos[3]=docente;
                                Datos[4]=ciclo;
                                Datos[5]=seccion;
                                Datos[6]=sementre;
                                modelo.addRow(Datos); 
                        }     
                     }
    }
    fis.close();
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

             ArrayList<String> ciclos=new ArrayList<String>();
             ArrayList<String> cursos=new ArrayList<String>();
             ArrayList<String> copiar=new ArrayList<String>();
            //-----------------------------------------------------------------
             File path2=new File("C:/EPIS/Ciclos");
             String explorardor2="";
             if(path2.exists()){
             String[] lista2=path2.list();
             for(int i=0;i<lista2.length;i++){
                explorardor2=lista2[i];
                ciclos.add(explorardor2);
              }
              File path3;
             for(int i=0;i<ciclos.size();i++){
                  path3=new File("C:\\EPIS\\Ciclos\\"+ciclos.get(i));
                  String explorardor3="";
                  if(path3.exists()){
                  String[] lista3=path3.list();
                  for(int j=0;j<lista3.length;j++){
                     explorardor3=lista3[j];
                     cursos.add(path3+"\\"+explorardor3);
                 }
                 }   
           }
            File path1=new File("C:/EPIS/copiar");
            String RutaServer=String.valueOf(path1);
            String explorardor="";
            if(path1.exists()){
            String[] lista=path1.list();
            for(int i=0;i<lista.length;i++){
                explorardor=lista[i];
                copiar.add(explorardor);
                }
           } 
              try{
                   for(int i=0;i<cursos.size();i++){
                    for(int j=0;j<copiar.size();j++){
                     File origen = new File(RutaServer+"\\"+copiar.get(j));  
                     String desti=cursos.get(i)+"\\"+copiar.get(j);
                     File destino = new File(desti);
                     if (origen.exists()) {
                        Files.copy(Paths.get(origen.getAbsolutePath()),
                        Paths.get(destino.getAbsolutePath()), StandardCopyOption.REPLACE_EXISTING);
                        }
                     }
              }
              }catch (Exception e) {e.printStackTrace();
            }
            }else{
                JOptionPane.showMessageDialog(null, "El Directorio no Existe....Primero Cree las Carpetas");
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_4_Ciclos_pastor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_4_Ciclos_pastor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_4_Ciclos_pastor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio_4_Ciclos_pastor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Ejercicio_4_Ciclos_pastor().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Ejercicio_4_Ciclos_pastor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabladatos;
    // End of variables declaration//GEN-END:variables
}
